LDFLAGS := -s USE_SDL=2 -s WASM=1
CFLAGS := -O3 -Werror -Wall -Wextra -pedantic -std=c90

CC := emcc

all: stars.html

run: stars.html
	emrun --no_browser --port 8080 $^

OBJS := stars.c
INC :=

stars.html: $(OBJS) $(INC)
	$(CC) $(CFLAGS) $(OBJS) $(LDFLAGS) -o $@

.PHONY: clean
clean:
	-rm -f stars.html stars.js stars.wasm
