LDFLAGS := -s USE_SDL=2 -s WASM=1
CFLAGS := -O3 -Werror -Wall -Wextra -pedantic -std=c90

CC := emcc

all: fire.html

run: fire.html
	emrun --no_browser --port 8080 $^

OBJS := fire.c firepal.c
INC := firepal.h

fire.html: $(OBJS) $(INC)
	$(CC) $(CFLAGS) $(OBJS) $(LDFLAGS) -o $@

.PHONY: clean
clean:
	-rm -f fire.html fire.js fire.wasm
