LDFLAGS := -s USE_SDL=2 -s WASM=1
CFLAGS := -O3 -Werror -Wall -Wextra -pedantic -std=c90

CC := emcc

all: plasma.html

run: plasma.html
	emrun --no_browser --port 8080 $^

OBJS := plasma.c plasmpal.c
INC := plasmpal.h

plasma.html: $(OBJS) $(INC)
	$(CC) $(CFLAGS) $(OBJS) $(LDFLAGS) -o $@

.PHONY: clean
clean:
	-rm -f plasma.html plasma.js plasma.wasm
